### ISSUE TITLE
Error in Building the image on Ubuntu 14.04

### ISSUE THREAD

**Issue by sam1ee** [yhfudev/arch-kali-odroidc1#5]
scripts/kconfig/conf --silentoldconfig Kconfig
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
make[1]: `include/generated/mach-types.h' is up to date.
  CALL    scripts/checksyscalls.sh
Build rootfs ...
Format arm already registered.
/home/iai/Downloads/kali-arm/arch-kali-odroidc1/src
[DBG] debootstrap state 1
[DBG] debootstrap --foreign --arch armhf kali '/home/iai/Downloads/kali-arm/arch-kali-odroidc1/src/rootfs-kali-armhf-kali-odroidc1-image'  http://http.kali.org/kali
I: Retrieving Release 
E: Failed getting release file http://http.kali.org/kali/dists/kali/Release
Error in debootstarap stage 1

Sam

**Comment by yhfudev** [comment]
It's due to the changed Kali repo url. It's fixed.
